### PR TITLE
Speed up beacon--movement->

### PR DESCRIPTION
**Pull request by tsdh**

### CODE REVIEW

**Comment by Malabarba** [comment]
We have to use the binary <= because beacon still supports older emacsen. 

Besides that, the logic looks solid. Does it run faster for you?

**Comment by tsdh** [comment]
Ok, I'll change that now.  Yes, it runs much, much faster.  With a delta of 35, it has to check at most 70 lines to decide if the movement was larger.  And if not, it shortcuts.  `count-screen-lines` always has to check all lines between the two positions, no matter if it are zero, thousand, or a million.

**Comment by tsdh** [comment]
Ups, wait, there's an error in it I'm going to fix right now.

**Comment by tsdh** [comment]
Ok, now it does the right thing.  The original version always tested if point was on the current line which is obviously always true.  But now with the correct logic which tests if the previous position is on the current line, it's still so fast that I can't see any difference to the buggy (but speed-wise optimal) version.

**Pull request merged**
