### PR TITLE
Fix a bug and add blink when window changes feature

### PR DESCRIPTION
**Pull request by tsdh**
There has been a bug when changing buffers where the blink code for
buffer changes and window scrolls has been triggered resulting in an
immediate blink followed by another blink (induced by window scroll)
just right after the next command.  Now the buffer change case
deactivates the window scroll blink in these cases.

And there's a new defcustom: beacon-blink-when-window-changes.  It does
exactly what it says.  Note that buffer changes don't subsume this
feature.  You can have many windows on the same buffer and switch
between those.

Also, now the overlays get a 'window property so that their blink is
only visible in the selected window.  Else, switching windows between 2
windows on the same buffer would show the beacon in both windows which
defeats its purpose.

### CODE REVIEW

**Comment by Malabarba** [comment]
Hi Tassilo, thanks for this again.
Unfortunately, I fixed some of this stuff myself yesterday and pushed this morning. To fix the double blink problem I just completely removed `blink-when-buffer-changes` (this functionality is now covered by the window scrolling). 

I still like your `blink-when-window-changes` and your code for displaying the overlay only in one window. Could you rebase those on top of current master?

**Comment by tsdh** [comment]
Yes, I'll do.

**Comment by tsdh** [comment]
Ok, there you go.

**Comment by Malabarba** [comment]
Great, thanks again!

**Pull request merged**
